<?php

/**
 * @file
 * Contains vipps_recurring_payments.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\user\Entity\Role;

/**
 * Implements hook_help().
 */
function vipps_recurring_payments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vipps_recurring_payments module.
    case 'help.page.vipps_recurring':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 module for vipps recurring payments') . '</p>';
      return $output;

    default:
  }
}

function vipps_recurring_payments_install() {
  $role_object = Role::load('manage own vipps agreements entities');
  $role_object->grantPermission('authenticated');
  $role_object->save();
}

/**
 * Implements hook_entity_operation().
 */
function vipps_recurring_payments_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
  $operations = array();
  $info = $entity->getEntityType();

  if($info->id() == 'vipps_agreements') {
    $account = \Drupal::currentUser();
    if ($account->hasPermission('manage own vipps agreements entities')) {
      $operations['manage-fields'] = array(
        'title' => t('Cancel agreement'),
        'weight' => 15,
        'url' => Url::fromRoute("entity.vipps_agreements.ask_cancel_form", [
          'vipps_agreements' => $entity->id(),
          'user' => \Drupal::currentUser()->id(),
        ]),
      );
    }
  }

  return $operations;
}

/**
 * hook_form_alter()
 */

function vipps_recurring_payments_form_alter (&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if($form_id == 'user_cancel_form') {
    $form['actions']['submit']['#submit'][] = 'vipps_recurring_payments_html_mails'; //custom name
  }
}

function vipps_recurring_payments_html_mails($form, \Drupal\Core\Form\FormStateInterface $form_state){
  $user = \Drupal::currentUser();
  $user_email = $user->getEmail();
  $site_mail = \Drupal::config('system.site')->get('mail');

  $send_mail = new \Drupal\Core\Mail\Plugin\Mail\PhpMail(); // this is used to send HTML emails
  $from = $user_email;
  $to = $site_mail;
  $message['headers'] = array(
    'content-type' => 'text/html',
    'MIME-Version' => '1.0',
    'reply-to' => $from,
    'from' => 'sender name <'.$from.'>'
  );
  $message['to'] = $to;
  $message['subject'] = "Subject Goes here !!!!!";

  $message['body'] = 'Hello,
  Thank you for reading this blog.';

  \Drupal::logger('vipps_user_cancel_agreement')->info(
    'Sending cancel email from %from to %to', ['%from' => $from, '%to' => $to]
  );

  $send_mail->mail($message);
}
