<?php

/**
 * @file
 * Contains vipps_recurring_payments.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\user\Entity\Role;
use Drupal\vipps_recurring_payments\Event\UserRequestCancelationEvent;

/**
 * Implements hook_help().
 */
function vipps_recurring_payments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vipps_recurring_payments module.
    case 'help.page.vipps_recurring':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 module for vipps recurring payments') . '</p>';
      return $output;

    default:
  }
}

function vipps_recurring_payments_install() {
  $role_object = Role::load('manage own vipps agreements entities');
  $role_object->grantPermission('authenticated');
  $role_object->save();
}

/**
 * Implements hook_entity_operation().
 */
function vipps_recurring_payments_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
  $operations = array();
  $info = $entity->getEntityType();

  if($info->id() == 'vipps_agreements') {
    $account = \Drupal::currentUser();
    if ($account->hasPermission('manage own vipps agreements entities')) {
      $operations['manage-fields'] = array(
        'title' => t('Cancel agreement'),
        'weight' => 15,
        'url' => Url::fromRoute("entity.vipps_agreements.user_cancel_form", [
          'vipps_agreements' => $entity->id(),
          'user' => \Drupal::currentUser()->id(),
        ]),
      );
    }
  }

  return $operations;
}
