<?php

/**
 * @file
 * Contains commerce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce module.
    case 'help.page.commerce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Use commerce with Vipps Recurring Payments') . '</p>';
      return $output;

    default:
  }
}
