<?php

/**
 * @file
 * Contains commerce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vipps_recurring_payments_commerce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce module.
    case 'help.page.vipps_recurring_payments_commerce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Use commerce with Vipps Recurring Payments') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function vipps_recurring_payments_commerce_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == 'commerce_billing_schedule_edit_form' || $form_id == 'commerce_billing_schedule_add_form') {
    $form['dunning']['#access'] = FALSE;
  }
}
